### ISSUE TITLE
Can not load iooxa.min.js

### ISSUE THREAD

**Issue by J2thearo** [rowanc1/ink#16]
Hello,
I'm very curious about iooxa. I was going to replace ink-components with it today, but I got a bug. Here is the basic index.html

![Screenshot 2020-07-07 21 10 38](https://user-images.githubusercontent.com/55392372/86830777-63c98500-c096-11ea-84f0-ba5ab2a1a93e.png)

I keep getting the error

![Screenshot 2020-07-07 21 13 04](https://user-images.githubusercontent.com/55392372/86831018-a9864d80-c096-11ea-9bdd-a95f8ce88383.png)

I have also already downloaded iooxa.min.js locally but still get the error. 

It would be great if you could help me out, thanks!

Many Greetings,
J2thearo

**Comment by rowanc1** [comment]
Hm, interesting - there could be a race condition with adding the web-components. I will investigate this in the next few days and get back to you here!

What browser/OS are you using?

**Comment by rowanc1** [comment]
Hey @J2thearo,

Starting to look at this today. I think I know where the bug is and will fix it.

I think this shouldn't actually stop the article from loading and becoming interactive though?

Can you try copying this locally?
https://jsbin.com/qulahusifa/5/edit?html,output

I do get that error, but everything actually works fine!

**Comment by rowanc1** [comment]
This should now be fixed in the deployed version:

Note that you may have to explicitly point your script at it, the forwarding sometimes takes a while to update.

`<script async src="https://unpkg.com/@iooxa/article@0.2.7/dist/iooxa.min.js"></script>`

**Comment by rowanc1** [comment]
Please let us know if you have any other problems upgrading from ink!!!

**Comment by J2thearo** [comment]
Hello Rowan, 
thanks for taking care of it. Yeah, you're right, I can use iooxa normally despite the bug. In my original code, I messed up ink and iooxa syntax, so I couldn't get started. I was sure it was because of the bug, but in the end I just have to get used to the new syntax. At the moment I'm going deeper into the documentation and I'm sure there is still a lot to learn.

**Comment by rowanc1** [comment]
Also, the best place to look for upgrading is here:
https://github.com/iooxa/article/releases/tag/v0.2.4

The name/value/bind was the pieces that likely give the most trouble. If you come across other things that don't make sense, don't hesitate to call them out as bugs! At the very least it means updating the documentation!
