### ISSUE TITLE
New Component: Dropdown Selector

### ISSUE THREAD

**Issue by rowanc1** [rowanc1/ink#9]
Mentioned recently by @lrq3000 and @bsmithyman.

**Comment by bsmithyman** [comment]
Oh, sweet
I'll try to have a look

**Comment by rowanc1** [comment]
@bsmithyman, I was just making a note of it. I am planning to come back around to `ink` in the next few weeks. I have the start of a refactor done, but it will take a bit to test it. Basically I am making the backend a bit more flexible so that it can plug into other redux architecture as well as moving the library to typescript.

**Comment by rowanc1** [comment]
This has been released in ink-basic!

https://www.npmjs.com/package/@iooxa/ink-basic
